<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * fb.Vendor_Order_Booking — the purchase order. F_B.ds:3088, 36 fields.
 * Reached in Creator through the nav item **Vendor Bills** (findings §8.7).
 *
 * Measured against 11,149 live orders — `fnb/FNB_DS_FINDINGS.md` §8.
 *
 * ORDER_FOR IS A DISCRIMINATOR, and the live data is clean enough to enforce it:
 *
 *     Against Booking  10,484 rows   booking set, warehouse NEVER set
 *     Location            213 rows   neither booking nor warehouse
 *     Warehouse            45 rows   warehouse set, booking NEVER set
 *
 * Zero rows carry both, so the CHECK below describes reality rather than adding a
 * rule. 407 further rows have NO order_for and no order number, vendor or amount —
 * malformed, rejected at import rather than loaded as zero-value orders (§8.2).
 * Hence order_for is nullable but constrained when present.
 *
 * MONEY — §8.3, confirmed on a real record and in aggregate:
 *
 *     amount      = SUM(line.amount)                          recomputed, not trusted
 *     grand_total = ROUND(amount + gst - discount)            to WHOLE RUPEES
 *     adjusted    = grand_total - (amount + gst - discount)   the remainder
 *     payable     = grand_total - paid
 *
 * `adjusted_amount` is deliberately NOT money-typed: Creator declares it
 * `type = decimal` and renders it without a ₹, because it is a rounding remainder.
 * Live range: -0.48 .. 0.50.
 *
 * VILLA IS NOT STORED HERE (§9.5). The Creator field exists but is empty on live
 * records and the Edit form does not render it; the export resolves villa through
 * the booking. So no villa_id column — derive it from the booking or the line
 * items, and treat a blank as normal rather than as missing data.
 *
 * `books_id` is a Zoho BOOKS id — 19 digits, prefix 2508841, same org as
 * coa_accounts.books_account_id (§4.1, §8.8). A string, like every id here. §17
 * says do not build the Books push; storing the id it returns is not the push.
 */
return new class extends Migration
{
    /** Creator's exact picklist values, spellings included. */
    private const ORDER_FOR = ['Warehouse', 'Against Booking', 'Location'];

    private const STATUS = ['Order Placed', 'Vendor Fulfilled', 'Order Received'];

    /**
     * NOTE `Payment Inprogress` — lowercase p. Accounts spells the same concept
     * `Payment InProgress` in two places already, so this is the THIRD variant in
     * the cluster, and 477 live rows carry it (§8.4). Preserved exactly: a status
     * comparison that normalised would silently match nothing.
     */
    private const PAYMENT_STATUS = ['Paid', 'Unpaid', 'Payment Inprogress', 'Partially Paid', 'Overpaid'];

    public function up(): void
    {
        Schema::create('fnb_vendor_order_bookings', function (Blueprint $table) {
            $table->id();
            $table->string('creator_id', 32)->nullable()->unique();

            // Generated by fb.Auto_Numbers.Vendor_Booking_Series — read-only on the
            // form (§9.4). Live format: EKO/F&BOrder/11430.
            $table->string('order_no')->nullable();

            $table->foreignId('vendor_id')->nullable()
                ->constrained('vendors')->nullOnDelete();

            $table->string('order_for')->nullable();
            $table->date('order_date')->nullable();

            // The three Order_for targets.
            $table->string('booking_no')->nullable();          // fb.Booking, not modelled yet
            $table->foreignId('fnb_warehouse_id')->nullable()
                ->constrained('fnb_warehouses')->nullOnDelete();
            $table->foreignId('location_id')->nullable()
                ->constrained('locations')->nullOnDelete();

            $table->foreignId('state_id')->nullable()
                ->constrained('states')->nullOnDelete();

            $table->string('request_no')->nullable();          // fb.Request_Stock_for_Food

            $table->string('status')->nullable();
            $table->string('payment_status')->nullable();
            $table->date('payment_due_date')->nullable();

            // Creator has billing_year + billing_month as separate inputs AND a
            // billing_cycle lookup. All three are kept: §6.4 is emphatic that the
            // cycle must already exist and must never be auto-created, so the raw
            // month and year are the evidence of what was asked for.
            $table->integer('billing_year')->nullable();
            $table->string('billing_month')->nullable();
            $table->foreignId('billing_cycle_id')->nullable()
                ->constrained('billing_cycles')->nullOnDelete();

            $table->decimal('total_quantity', 16, 4)->nullable();   // SUM(line.received)
            $table->decimal('amount', 16, 4)->nullable();           // SUM(line.amount)
            $table->decimal('gst_amount', 16, 4)->nullable();
            $table->decimal('discount', 16, 4)->nullable();         // only editable money field
            $table->decimal('grand_total', 16, 4)->nullable();
            $table->decimal('adjusted_amount', 10, 4)->nullable();  // remainder, not money
            $table->decimal('paid_amount', 16, 4)->nullable();
            $table->decimal('payable_amount', 16, 4)->nullable();

            $table->string('books_id', 32)->nullable();

            $table->boolean('update_fulfilled_qty')->default(false);
            $table->boolean('update_received_qty')->default(false);
            $table->boolean('expense_updated')->default(false);
            $table->boolean('order_received')->default(false);      // Creator: Order_recived

            $table->text('particulars')->nullable();

            $table->string('added_user')->nullable();
            $table->timestamp('creator_added_time')->nullable();
            $table->string('modified_user')->nullable();
            $table->timestamp('creator_modified_time')->nullable();

            $table->timestamps();

            // order_no is NOT unique. Accounts has 233 payment numbers shared by 494
            // rows; until this export is checked the same way, a unique index would
            // reject live data on import.
            $table->index('order_no');
            $table->index(['order_for', 'order_date']);
            $table->index('vendor_id');
        });

        $list = fn (array $v) => "'".implode("','", $v)."'";

        DB::statement(
            'ALTER TABLE fnb_vendor_order_bookings ADD CONSTRAINT fnb_vob_order_for_check '
            .'CHECK (order_for IS NULL OR order_for IN ('.$list(self::ORDER_FOR).'))'
        );

        DB::statement(
            'ALTER TABLE fnb_vendor_order_bookings ADD CONSTRAINT fnb_vob_status_check '
            .'CHECK (status IS NULL OR status IN ('.$list(self::STATUS).'))'
        );

        DB::statement(
            'ALTER TABLE fnb_vendor_order_bookings ADD CONSTRAINT fnb_vob_payment_status_check '
            .'CHECK (payment_status IS NULL OR payment_status IN ('.$list(self::PAYMENT_STATUS).'))'
        );

        // The discriminator, as measured: a Warehouse order never carries a booking,
        // an Against-Booking order never carries a warehouse, a Location order
        // carries neither. Holds on all 11,149 live rows.
        DB::statement(
            'ALTER TABLE fnb_vendor_order_bookings ADD CONSTRAINT fnb_vob_order_for_target_check '
            ."CHECK (\n"
            ."  order_for IS NULL\n"
            ."  OR (order_for = 'Warehouse'       AND booking_no IS NULL)\n"
            ."  OR (order_for = 'Against Booking' AND fnb_warehouse_id IS NULL)\n"
            ."  OR (order_for = 'Location'        AND booking_no IS NULL AND fnb_warehouse_id IS NULL)\n"
            .')'
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('fnb_vendor_order_bookings');
    }
};
