<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * fb.Request_Stock_for_Food — the kitchen's request, and the parent of the raw
 * material lines. F_B.ds:2283. Nav label: **Request Stock for Food**.
 *
 * 4,328 live requests. Findings §11.
 *
 * This is where an order originates: a request is raised against a booking, its
 * lines become `fnb_raw_material_requests`, and those in turn drive
 * `fnb_vendor_order_booking_items.ordered_quantity` — which is why that field is
 * read-only in the Items Ordered grid (§9.4).
 *
 * GUEST NAME IS PII AND IS STORED HERE. The export carries real guest names beside
 * villa and stay dates. `master-data/` is git-ignored wholesale for this reason
 * (§10). Any read API over this table needs authorisation before exposure — the
 * same gap CLAUDE.md flags on vendors, which carry PANs with no gate on them.
 *
 * `booking_no` is a STRING, not a foreign key: fb.Booking is the 52-field
 * stay-booking master owned by another app and is not modelled here.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('fnb_request_stock_for_foods', function (Blueprint $table) {
            $table->id();
            $table->string('creator_id', 32)->nullable()->unique();

            // Generated by fb.Auto_Numbers.Request_Series. Live format: EKO/Stock/4392.
            $table->string('request_no')->nullable();

            $table->string('booking_no')->nullable();
            $table->string('booking_number')->nullable();   // a SECOND booking column in the export

            $table->foreignId('villa_id')->nullable()
                ->constrained('villas')->nullOnDelete();
            $table->foreignId('location_id')->nullable()
                ->constrained('locations')->nullOnDelete();
            $table->foreignId('fnb_warehouse_id')->nullable()
                ->constrained('fnb_warehouses')->nullOnDelete();

            // PII. See the class docblock.
            $table->text('guest_name')->nullable();

            $table->date('checked_in_date')->nullable();
            $table->date('check_out_date')->nullable();

            $table->text('chef_name')->nullable();          // fb.Chef_Master, by name in the export
            $table->string('status')->nullable();
            $table->boolean('request_raised')->default(false);
            $table->string('request_from')->nullable();     // Warehouse | Order from Vendor
            $table->text('remarks')->nullable();

            $table->string('added_user')->nullable();
            $table->timestamp('creator_added_time')->nullable();
            $table->string('modified_user')->nullable();
            $table->timestamp('creator_modified_time')->nullable();

            $table->timestamps();

            $table->index('request_no');
            $table->index('booking_no');
            $table->index(['status', 'request_raised']);
        });

        // `Request_From` is the discriminator that decides which of the duplicated
        // Warehouse_Name / Vendor_Name pairs is live on the child rows (§11.2/§11.3).
        DB::statement(
            'ALTER TABLE fnb_request_stock_for_foods ADD CONSTRAINT fnb_rsf_request_from_check '
            ."CHECK (request_from IS NULL OR request_from IN ('Warehouse','Order from Vendor'))"
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('fnb_request_stock_for_foods');
    }
};
